### ISSUE TITLE
Шарманка не играет

### ISSUE THREAD

**Issue by ridouchire** [nesorter/nesorter#10]
После запуска `docker-compose up` и некоторого ожидания(что было несколько неочевидно, хотелось бы явности) получаю что-то вроде такого:

```
~/Sources/nesorter(main|-1) docker-compose up
Starting icecast2       ... done
Starting nesorter_api_1 ... done
Attaching to icecast2, nesorter_api_1
icecast2    |  * Starting streaming media server icecast2
icecast2    | [2022-08-23  01:23:25] WARN CONFIG/_parse_root Warning, <hostname> not configured, using default value "localhost". This will cause problems, e.g. with YP directory listings.
icecast2    | WARNING: Can't change user id unless you are root.
icecast2    | [2022-08-23  01:23:25] WARN fserve/fserve_recheck_mime_types Cannot open mime types file /etc/mime.types
icecast2    |    ...done.
icecast2    | [2022-08-23  01:18:30] INFO yp/yp_update_thread YP update thread started
icecast2    | [2022-08-23  01:18:30] INFO connection/get_ssl_certificate No SSL capability on any configured ports
icecast2    | [2022-08-23  01:18:30] INFO stats/_stats_thread stats thread started
icecast2    | [2022-08-23  01:18:31] DBUG slave/_slave_thread checking master stream list
icecast2    | [2022-08-23  01:20:31] DBUG slave/_slave_thread checking master stream list
icecast2    | [2022-08-23  01:22:31] DBUG slave/_slave_thread checking master stream list
icecast2    | [2022-08-23  01:23:25] INFO main/main Icecast 2.4.4 server started
icecast2    | [2022-08-23  01:23:25] DBUG yp/yp_recheck_config Updating YP configuration
icecast2    | [2022-08-23  01:23:25] INFO yp/yp_update_thread YP update thread started
icecast2    | [2022-08-23  01:23:25] INFO connection/get_ssl_certificate No SSL capability on any configured ports
api_1       | yarn run v1.22.19
api_1       | $ prisma migrate dev
icecast2    | [2022-08-23  01:23:25] INFO stats/_stats_thread stats thread started
icecast2    | [2022-08-23  01:23:26] DBUG slave/_slave_thread checking master stream list
icecast2    | [2022-08-23  01:25:10] DBUG auth/add_authenticated_listener Stats request, sending XSL transformed stats
icecast2    | [2022-08-23  01:25:10] DBUG fserve/fserve_add_client Adding client to file serving engine
icecast2    | [2022-08-23  01:25:10] DBUG fserve/fserve_add_pending fserve handler waking up
icecast2    | [2022-08-23  01:25:10] DBUG fserve/fserv_thread_function fserve handler exit
icecast2    | [2022-08-23  01:25:10] DBUG stats/modify_node_event update global clients (1)
icecast2    | [2022-08-23  01:25:10] DBUG stats/modify_node_event update global connections (1)
icecast2    | [2022-08-23  01:25:10] DBUG stats/modify_node_event update global client_connections (1)
icecast2    | [2022-08-23  01:25:10] DBUG stats/modify_node_event update global clients (0)
icecast2    | [2022-08-23  01:25:10] INFO fserve/fserve_client_create checking for file /style.css (/etc/icecast2/web/style.css)
icecast2    | [2022-08-23  01:25:10] DBUG fserve/fserve_add_client Adding client to file serving engine
icecast2    | [2022-08-23  01:25:10] DBUG fserve/fserve_add_pending fserve handler waking up
icecast2    | [2022-08-23  01:25:10] DBUG fserve/fserv_thread_function fserve handler exit
icecast2    | [2022-08-23  01:25:10] INFO fserve/fserve_client_create checking for file /icecast.png (/etc/icecast2/web/icecast.png)
icecast2    | [2022-08-23  01:25:10] WARN fserve/fserve_client_create req for file "/etc/icecast2/web/icecast.png" No such file or directory
icecast2    | [2022-08-23  01:25:10] DBUG fserve/fserve_add_client Adding client to file serving engine
icecast2    | [2022-08-23  01:25:10] DBUG fserve/fserve_add_pending fserve handler waking up
icecast2    | [2022-08-23  01:25:10] DBUG fserve/fserv_thread_function fserve handler exit
icecast2    | [2022-08-23  01:25:10] DBUG stats/modify_node_event update global clients (1)
icecast2    | [2022-08-23  01:25:10] DBUG stats/modify_node_event update global connections (2)
icecast2    | [2022-08-23  01:25:10] DBUG stats/modify_node_event update global client_connections (2)
icecast2    | [2022-08-23  01:25:10] DBUG stats/modify_node_event update global file_connections (1)
icecast2    | [2022-08-23  01:25:10] DBUG stats/modify_node_event update global clients (0)
icecast2    | [2022-08-23  01:25:10] DBUG stats/modify_node_event update global clients (1)
icecast2    | [2022-08-23  01:25:10] DBUG stats/modify_node_event update global connections (3)
icecast2    | [2022-08-23  01:25:10] DBUG stats/modify_node_event update global client_connections (3)
icecast2    | [2022-08-23  01:25:10] DBUG stats/modify_node_event update global clients (0)
icecast2    | [2022-08-23  01:25:26] DBUG slave/_slave_thread checking master stream list
api_1       | Error: request to https://binaries.prisma.sh/all_commits/2b0c12756921c891fec4f68d9444e18c7d5d4a6a/debian-openssl-1.1.x/libquery_engine.so.node.sha256 failed, reason: connect ETIMEDOUT 108.156.22.32:443
api_1       | error Command failed with exit code 1.
api_1       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
api_1       | ==> output.backend <==
api_1       | test
api_1       | 
api_1       | ==> output.frontend <==
api_1       | 
api_1       | ==> output.backend <==
api_1       | 1s] [INFO] [APP] Server start listening on 3001
api_1       | [0.035s] [INFO] [APP] Sockets cleaned
api_1       | [0.036s] [INFO] [APP] Socket created at /tmp/output_socket.mp3
api_1       | [0.036s] [INFO] [APP] Socket created at /tmp/listen_socket_0.mp3
api_1       | [0.036s] [INFO] [APP] Socket created at /tmp/listen_socket_1.mp3
api_1       | /app/node_modules/@prisma/client/runtime/index.js:45411
api_1       |         throw new PrismaClientInitializationError(message, this.client._clientVersion);
api_1       |               ^
api_1       | 
api_1       | PrismaClientInitializationError: 
api_1       | Invalid `this.db.fSItem.findMany()` invocation in
api_1       | /app/dist/Scanner/index.js:41:44
api_1       | 
api_1       |   38 async createChain() {
api_1       |   39     let time = Date.now();
api_1       |   40     const chain = {};
api_1       | → 41     const items = await this.db.fSItem.findMany()
api_1       |   Query engine library for current platform "debian-openssl-1.1.x" could not be found.
api_1       | You incorrectly pinned it to debian-openssl-1.1.x
api_1       | 
api_1       | This probably happens, because you built Prisma Client on a different platform.
api_1       | (Prisma Client looked in "/app/node_modules/@prisma/client/runtime/libquery_engine-debian-openssl-1.1.x.so.node")
api_1       | 
api_1       | Searched Locations:
api_1       | 
api_1       |   /app/node_modules/.prisma/client
api_1       |   /app/node_modules/@prisma/client
api_1       |   /app/node_modules/@prisma/client
api_1       |   /app/node_modules/.prisma/client
api_1       |   /app/prisma
api_1       |   /tmp/prisma-engines
api_1       |   /app/node_modules/.prisma/client
api_1       | 
api_1       | 
api_1       | To solve this problem, add the platform "debian-openssl-1.1.x" to the "binaryTargets" attribute in the "generator" block in the "schema.prisma" file:
api_1       | generator client {
api_1       |   provider      = "prisma-client-js"
api_1       |   binaryTargets = ["native"]
api_1       | }
api_1       | 
api_1       | Then run "prisma generate" for your changes to take effect.
api_1       | Read more about deploying Prisma Client: https://pris.ly/d/client-generator
api_1       |     at Object.request (/app/node_modules/@prisma/client/runtime/index.js:45411:15)
api_1       |     at async PrismaClient._request (/app/node_modules/@prisma/client/runtime/index.js:46301:18)
api_1       |     at async Scanner.createChain (/app/dist/Scanner/index.js:41:23) {
api_1       |   clientVersion: '3.14.0',
api_1       |   errorCode: undefined
api_1       | }
api_1       | 
api_1       | ==> output.frontend <==
api_1       | Listening on http://c332e546c067:3000, http://127.0.0.1:3000, http://172.19.0.3:3000
api_1       | 1:26:56 AM: Middleware error
api_1       | Error: connect ECONNREFUSED 127.0.0.1:3001
api_1       |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
```

Ставлю 4 звезды, и то за столько чтива.

**Comment by ridouchire** [comment]
После изменения в `srv/src/config.ts` параметра `API_LISTEN_PORT` с 3001 на 3000 - немного работает.

**Comment by kugimiya** [comment]
Кажется проблема не в listen port, а в окружении в котором пытается работать prisma. Буду разбираться.

**Comment by kugimiya** [comment]
@ridouchire, какая ОСь используется в качестве хоста?

**Comment by kugimiya** [comment]
@ridouchire, для ясности: да, api слушает 3001 порт, а сервер статики фронтенда слушает 3000 порт; фронт ходит в api просто по урлу на свой же сервер (получается что в 3000 порт); магия в том, что сервер статики проксирует все `hostname:3000/api` запросы на `hostname:3001/api`

**Comment by kugimiya** [comment]
@ridouchire, запушил фикс, кажется теперь должно работать. Порт бекенда лучше вернуть в 3001.

Из изменений, это docker-compose.yml, докерфайл образа, фиксы в коде апишки и всякий workaround.

Можешь вообще в целом заново пройтись по обновленному разделу "запуск в докер" README, вроде там немного действий на самом деле и разбросал по полочкам.
